project_name: terraform-provider-hrobot

# Build static binaries for all target platforms
builds:
  - id: provider
    main: ./cmd/terraform-provider-hrobot
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    # Terraform/OpenTofu convention: binary includes version with 'v' prefix
    binary: "terraform-provider-hrobot_v{{ .Version }}"
    ldflags:
      - -s -w

# Zip per platform with Terraform/OpenTofu-friendly names
archives:
  - id: provider_zips
    builds: [provider]
    format: zip
    # => terraform-provider-hrobot_0.1.0_linux_amd64.zip etc.
    name_template: "terraform-provider-hrobot_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

# Produce the checksum file that registries expect
checksum:
  name_template: "terraform-provider-hrobot_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

# Sign ONLY the checksum file (this creates ...SHA256SUMS.sig)
signs:
  - id: checksum
    artifacts: checksum
    cmd: gpg
    args:
      - --armor
      - --batch
      - --yes
      - --local-user
      - "{{ .Env.GPG_KEY }}"
      - --output
      - "${artifact}.sig"
      - --detach-sign
      - "${artifact}"

release:
  # Attach archives + SHA256SUMS + SHA256SUMS.sig to the GitHub Release
  draft: false
  replace_existing_draft: true
  mode: replace
