name: Release provider
on:
  push:
    tags: ["v*.*.*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with: { go-version: "1.22" }

      - name: Test
        run: go test ./...

      # Import the GPG key used to sign SHA256SUMS
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          # passphrase: ${{ secrets.GPG_PASSPHRASE }}
      # The action exports GPG-related env vars; we’ll use the fingerprint as GPG_KEY
      - name: Set GPG key env
        run: echo "GPG_KEY=${GPG_FINGERPRINT}" >> $GITHUB_ENV

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_KEY: ${{ env.GPG_KEY }}
